Codigos/app/routes/estado_sesion.py
from flask import render_template,request,redirect,url_for,Blueprint
from flask_login import login_user, logout_user
from app.modelos import *
import bcrypt

estado_sesion = Blueprint('estado_sesion', __name__,template_folder='templates')


@estado_sesion.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        usuario = request.form['username']
        contrasena = request.form['password']
        user =  Usuario.query.filter_by(nombre_usuario=usuario).first()
        if user and bcrypt.checkpw(contrasena.encode('utf-8'), user.contrasena_hash.encode('utf-8')):
            login_user(user)
            return redirect(url_for('pantallas_generales.catalogo'))
        else:
            error = "Login fallido. Por favor, intenta de nuevo."
            return render_template('login.html', error=error)
    return render_template('login.html')


@estado_sesion.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('pantallas_generales.inicio'))

Codigos/app/routes/modificacion_auto.py
#Imports
from flask import render_template,request,redirect,url_for,Blueprint
from app.modelos import *
from app.__init__ import*
from flask_login import login_required
import app.routes.script_adicionales.funciones_webscraping as fw


modificacion_auto = Blueprint('modificacion_auto', __name__,template_folder='templates')

@modificacion_auto.route('/agregar_auto', methods=['GET', 'POST'])
def agregar_auto():
    db.session.query(Libros_automaticos).delete()
    db.session.commit()
    if request.method == 'POST':
        if 'btn_buscar_web' in request.form:
            busqueda = request.form.get('busqueda_web')
            libros = fw.buscar_libro(busqueda)
            for libro in libros:
                if libro[2]==True:
                    nuevo_libro = Libros_automaticos(
                    auto_id=libro[0],
                    titulo=libro[3],
                    isbn=libro[4]+','+libro[5],
                    editorial=libro[6],
                    año_publicacion=libro[7],
                    descripcion=libro[8],
                    url_imagen=libro[9]
                    )
                    db.session.add(nuevo_libro)
                    db.session.commit()
        return render_template('agregar_auto.html', libros=libros)
    return render_template('agregar_auto.html')
    
    
@modificacion_auto.route('/edicion_auto/<string:auto_id>', methods=['GET', 'POST'])

def editar_libro_auto(auto_id):
    libro = Libros_automaticos.query.get_or_404(auto_id)
    if request.method == 'POST':
        descripcion_defecto = "Descripción no proporcionada"
        estudio_defecto = ""
        nuevo_libro = Libros(
            titulo=request.form['titulo'],
            isbn=request.form['isbn'],
            editorial=request.form['editorial'],
            descripcion=request.form['descripcion'] if request.form['descripcion'] else descripcion_defecto,
            año_publicacion=request.form['año_publicacion'],
            puntuacion=request.form['puntuacion'],
            ubicacion_estudio=request.form['ubicacion_estudio'] if request.form['ubicacion_estudio'] else estudio_defecto,
            url_imagen=request.form['url_imagen']
        )
        db.session.add(nuevo_libro)
        db.session.query(Libros_automaticos).delete()
        fecha_modificacion.actualizar_fecha_modificacion()
        db.session.commit()
        return redirect(url_for('pantallas_generales.catalogo'))
    return render_template('editar_libro.html', libro=libro)


@modificacion_auto.route('/combinacion_auto', methods=['GET', 'POST'])
def combinacion_auto():
    libros = Libros_automaticos.query.all()
    titulo=[]
    isbn=[]
    editorial=[]
    descripcion=[]
    año_publicacion=[]
    url_imagen=[]
    for libro in libros:
        titulo.append(libro.titulo)
        isbn.append(libro.isbn)
        editorial.append(libro.editorial)
        descripcion.append(libro.descripcion)
        año_publicacion.append(libro.año_publicacion)
        url_imagen.append(libro.url_imagen)
        
    if request.method == 'POST':
        descripcion_defecto = "Descripción no proporcionada"
        estudio_defecto = ""
        nuevo_libro = Libros(
            titulo=request.form['titulo'],
            isbn=request.form['isbn'],
            editorial=request.form['editorial'],
            descripcion=request.form['descripcion'] if request.form['descripcion'] else descripcion_defecto,
            año_publicacion=request.form['año_publicacion'],
            puntuacion=request.form['puntuacion'],
            ubicacion_estudio=request.form['ubicacion_estudio'] if request.form['ubicacion_estudio'] else estudio_defecto,
            url_imagen=request.form['url_imagen']
        )
        db.session.add(nuevo_libro)
        db.session.query(Libros_automaticos).delete()
        fecha_modificacion.actualizar_fecha_modificacion()
        db.session.commit()
        return redirect(url_for('pantallas_generales.catalogo'))
    return render_template('combinacion_auto.html', titulo=titulo, isbn=isbn, editorial=editorial, descripcion=descripcion, año_publicacion=año_publicacion, url_imagen=url_imagen)

Codigos/app/routes/modificacion_libros.py
from flask import render_template,request,redirect,url_for,Blueprint
from flask_login import login_required
from app.modelos import *
from app.__init__ import *

modificacion_libros = Blueprint('modificacion_libros', __name__,template_folder='templates')


@modificacion_libros.route('/agregar', methods=['GET', 'POST'])
@login_required
def agregar_libro():
    if request.method == 'POST':
        descripcion_defecto = "Descripción no proporcionada"
        estudio_defecto = ""
        nuevo_libro = Libros(
            titulo=request.form['titulo'],
            isbn=request.form['isbn'],
            editorial=request.form['editorial'],
            descripcion=request.form['descripcion'] if request.form['descripcion'] else descripcion_defecto,
            año_publicacion=request.form['año_publicacion'],
            puntuacion=request.form['puntuacion'],
            ubicacion_estudio=request.form['ubicacion_estudio'] if request.form['ubicacion_estudio'] else estudio_defecto,
            url_imagen=request.form['url_imagen']
        )
        db.session.add(nuevo_libro)
        fecha_modificacion.actualizar_fecha_modificacion()
        db.session.commit()
        return redirect(url_for('pantallas_generales.catalogo'))
    return render_template('agregar_libro.html')


@modificacion_libros.route('/edicion/<int:id>', methods=['GET', 'POST'])
@login_required
def editar_libro(id):
    libro = Libros.query.get_or_404(id)
    if request.method == 'POST':
        libro.titulo = request.form['titulo']
        libro.isbn = request.form['isbn']
        libro.editorial = request.form['editorial']
        libro.descripcion = request.form['descripcion']
        libro.año_publicacion = request.form['año_publicacion']
        libro.puntuacion = request.form['puntuacion']
        libro.ubicacion_estudio = request.form['ubicacion_estudio']
        libro.url_imagen = request.form['url_imagen']
        
        fecha_modificacion.actualizar_fecha_modificacion()
        db.session.commit()
        return redirect(url_for('pantallas_generales.catalogo'))
    return render_template('editar_libro.html', libro=libro)

@modificacion_libros.route('/eliminar/<int:id>')
@login_required
def eliminar_libro(id):
    libro = Libros.query.get_or_404(id)
    db.session.delete(libro)
    
    fecha_modificacion.actualizar_fecha_modificacion()
    db.session.commit()
    return redirect(url_for('pantallas_generales.catalogo'))

Codigos/app/routes/pantallas_generales.py
#Imports
from flask import render_template,request,Blueprint
from app.modelos import *
from app.routes.script_adicionales.importar_exportar import exportar_csv, importar_csv

pantallas_generales = Blueprint('pantallas_generales', __name__,template_folder='templates')


@pantallas_generales.route("/", methods=['GET', 'POST'])
def inicio():
    if request.method == 'POST':
        busqueda = request.form.get('busqueda_inicio')
        libros = Libros.query.filter((Libros.titulo.contains(busqueda)) | (Libros.isbn.contains(busqueda))).all()   
        fecha = fecha_modificacion.query.get_or_404(1)
        return render_template('catalogo.html', libros=libros, fecha=fecha)
    else:
        return render_template("inicio.html")
 
@pantallas_generales.route("/catalogo", methods=['GET', 'POST'])   
def catalogo():
    if request.method == 'POST':
        if 'btn_exportar' in request.form:
            return exportar_csv()
        elif 'btn_buscar' in request.form:
            busqueda = request.form.get('busqueda')
            libros = Libros.query.filter((Libros.titulo.contains(busqueda)) | (Libros.isbn.contains(busqueda))).all()
        elif 'archivo_csv' in request.files:
            archivo = request.files['archivo_csv']
            print('Archivo recibido')
            return importar_csv(archivo)
    else:
        libros = Libros.query.all()
    fecha=fecha_modificacion.query.get_or_404(1)
    return render_template('catalogo.html', libros=libros, fecha=fecha)

@pantallas_generales.route('/informacion/<int:id>', methods=['GET'])
def informacion_libro(id):
    libro = Libros.query.get_or_404(id)
    return render_template('informacion_libro.html', libro=libro)

@pantallas_generales.route('/calculadora', methods=['GET','POST'])
def calculadora():
    return render_template('calculadora.html')

Codigos/app/templates/agregar_auto.html
{% extends 'base.html' %}

{% block title %}Busqueda automática de libros{% endblock %}

{% block content %}
<div class="container">
    <h3>Localizador de libros en la web</h3>
    <!-- Formulario de Búsqueda -->
    <form method="POST" action="{{ url_for('modificacion_auto.agregar_auto') }}"  enctype="multipart/form-data">
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="Buscar por ISBN o Título" name="busqueda_web">
            <button class="btn btn-outline-secondary" type="submit" name="btn_buscar_web">Buscar</button>
        </div>
    </form>
    
    <div id="spinner" class="spinner-style-agregar-auto text-center">
        <div class="spinner-border text-primary" role="status">
            <span class="visually-hidden">Cargando...</span>
        </div>
    </div>


    


        {% for libro in libros %}
        <div class="mb-3">
            <div class="d-flex justify-content-between align-items-center">
                <h2 class="mb-0">{{ libro[0] }}</h2>
                <img src="{{ url_for('static', filename='img/'+ libro[1]) }}" class="logo-style-agregar-auto logo" alt="Logo de {{ libro[0] }}"> 
        </div>

        {% if libro[2]==True%}
        <div class="card-style-agregar-auto card mb-4">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="{{ libro[9] }}" class="img-fluid rounded-start card-img" alt="{{ libro[0] }}">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">{{ libro[3] }}</h5>
                        <p class="card-text">ISBN-10: {{ libro[4] }}</p>
                        <p class="card-text">ISBN-13: {{ libro[5] }}</p>
                        <p class="card-text">Editorial: {{ libro[6] }}</p>
                        <p class="card-text">Fecha de Publicación: {{ libro[7] }}</p>
                        <p class="card-text">Descripción: {{ libro[8] }}</p>
                    </div>
                </div>
            </div>
        </div>

        {% else %}
        <h4>No se ha encontrado información en esta fuente</h4>
        <hr>
    
        {% endif %}
        {% endfor %}


        {% if libros%}
        <div class="container my-4 text-center">
            <h4 class="mb-4">Seleccione el proveedor de información deseado o personalizalo</h4>
            <div class="d-flex  justify-content-between align-items-center">
                <a href="/agregar" class="btn btn-primary">Búsqueda Manual</a>
                {% for libro in libros %}
                    {% if libro[2] %}

                        <a href="{{ url_for('modificacion_auto.editar_libro_auto', auto_id=libro[0]) }}" class="btn btn-outline-primary">
                            <img src="{{ url_for('static', filename='img/'+ libro[1]) }}" class="logo" alt="Logo de {{ libro[0] }}" style="height: 20px;"> 
                        </a>
                    {% endif %}
                {% endfor %}
                <a href="/combinacion_auto" class="btn btn-primary">Combinar fuentes</a>
            </div>
        </div>
        {% endif %}
</div>



<script>
    document.addEventListener('DOMContentLoaded', function() {
        var form = document.querySelector('form');
        var spinner = document.getElementById('spinner');
        spinner.style.display = 'none'; 
    
        form.addEventListener('submit', function() {

            spinner.style.display = 'block';
        });
    });
</script>

{% endblock %}

Codigos/app/templates/agregar_libro.html
{% extends "base.html" %}

{% block title %}
Agregar Libro
{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2>Agregar Nuevo Libro</h2>
    <form action="/agregar" method="POST">
        <div class="mb-3">
            <label for="titulo" class="form-label">Título</label>
            <input type="text" class="form-control" id="titulo" name="titulo" required>
        </div>
        <div class="mb-3">
            <label for="isbn" class="form-label">ISBN</label>
            <input type="text" class="form-control" id="isbn" name="isbn" required>
        </div>
        <div class="mb-3">
            <label for="editorial" class="form-label">Editorial</label>
            <input type="text" class="form-control" id="editorial" name="editorial">
        </div>
        <div class="mb-3">
            <label for="descripcion" class="form-label">Descripción</label>
            <textarea class="form-control" id="descripcion" name="descripcion" rows="3"></textarea>
        </div>
        <div class="mb-3">
            <label for="año_publicacion" class="form-label">Año de publicación</label>
            <input type="text" class="form-control" id="año_publicacion" name="año_publicacion">
        </div>
        <div class="mb-3">
            <label for="puntuacion" class="form-label">Puntuación</label>
            <select class="form-select" id="puntuacion" name="puntuacion">
                <option> </option>
                <option value="0">0</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select>
        </div>
        <div class="mb-3">
            <label for="ubicacion_estudio" class="form-label">Ubicación del estudio</label>
            <input type="text" class="form-control" id="ubicacion_estudio" name="ubicacion_estudio">
        </div>
        <div class="mb-3">
            <label for="url_imagen" class="form-label">URL de la imagen</label>
            <input type="text" class="form-control" id="url_imagen" name="url_imagen">
        </div>
        <button type="submit" class="btn btn-primary">Agregar Libro</button>
    </form>
</div>
{% endblock %}

Codigos/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="../static/css/styles.css">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

    <nav class="navbar-style-base navbar navbar-expand-lg" >
        <div class="container-fluid">
            <a class="navbar-brand" href="/">
                <img src="../static/img/principal-logo.png" alt="Logo" width="30" height="30" class="logo-style-base d-inline-block align-top">
                Clasificador de libros</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="/">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/catalogo">Catálogo</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/">Guía de analisis</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/">Decálogo</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/">Referentes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/">Guía de puntuación</a>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto"> 
                    {% if current_user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('estado_sesion.logout') }}">{{ current_user.nombre_usuario}} (Desconectar)</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('estado_sesion.login') }}">Login</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    


    {% block content%}
    {% endblock %}
    <div class="div-center-style-base text-center" >
        <img src="../static/img/logo-ubu.svg" alt="Logo" width="150px" height="50px" class="d-inline-block align-top" style="margin-right: 10px;">
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

Codigos/app/templates/calculadora.html
{%extends 'base.html'%}

{%block title%}Inicio{%endblock%}

{%block content%}
<div class="container py-5">
    <h2 class="mb-3">Formulario de Cálculos</h2>
    <form id="calculoForm">
        <div class="mb-3">
            <label for="inputImagenNina" class="form-label">Masculino Genérico</label>
            <input type="checkbox"  id="masculino" name="masculino">
        </div>
        <div class="mb-3">
            <label for="inputImagenNina" class="form-label">Imagen Niña</label>
            <input type="number" class="form-control" id="inputImagenNina" name="imagen_nina" placeholder="0">
        </div>
        <div class="mb-3">
            <label for="inputImagenNino" class="form-label">Imagen Niño</label>
            <input type="number" class="form-control" id="inputImagenNino" name="imagen_nino" placeholder="0">
        </div>
        <div class="mb-3">
            <label for="inputImagenMujer" class="form-label">Imagen Mujer</label>
            <input type="number" class="form-control" id="inputImagenMujer" name="imagen_mujer" placeholder="0">
        </div>
        <div class="mb-3">
            <label for="inputImagenHombre" class="form-label">Imagen Hombre</label>
            <input type="number" class="form-control" id="inputImagenHombre" name="imagen_hombre" placeholder="0">
        </div>

        <div class="mt-4">
            <button type="button" class="btn btn-primary" onclick="ajustarPorcentajes()">Calcular</button>
        </div>

        <div id="resultadoPorcentajes" class="mt-3"></div>
    </form>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
    document.getElementById("calcularBtn").addEventListener("click", ajustarPorcentajes);
});

function ajustarPorcentajes() {
    var masculino = document.getElementById('masculino').checked;
    var nina = parseInt(document.getElementById('inputImagenNina').value || 0);
    var nino = parseInt(document.getElementById('inputImagenNino').value || 0);
    var mujer = parseInt(document.getElementById('inputImagenMujer').value || 0);
    var hombre = parseInt(document.getElementById('inputImagenHombre').value || 0);
    
    var total_nino=(nino+nina)
    var p_nino=(100*nino)/(total_nino)
    var p_nina=(100*nina)/(total_nino)
    
    var total_adulto=(mujer+hombre)
    var p_mujer=(mujer)/(total_adulto)*100
    var p_hombre=(hombre)/(total_adulto)*100

    if (p_nino<p_nina) {
        var porcentaje_ninos=(p_nino*100)/50;
    }
    else if (p_nina<p_nino){
        var porcentaje_ninos=(p_nina*100)/50;
    }
    else if (p_nina==p_nino){
        var porcentaje_ninos=50;
    }

    if (p_hombre<p_mujer) {
        var porcentaje_adulto=(p_hombre*100)/50;
    }
    else if (p_mujer<p_hombre){
        var porcentaje_adulto=(p_mujer*100)/50;
    }
    else if (p_mujer==p_hombre){
        var porcentaje_adulto=50;
    }


    var resultadoHTML = `
        <p>Porcentaje Adulto: ${porcentaje_adulto}%</p>
        <p>Porcentaje Niños: ${porcentaje_ninos}%</p>
  
    `;
    document.getElementById('resultadoPorcentajes').innerHTML = resultadoHTML;
}
</script>

{%endblock%}

Codigos/app/templates/catalogo.html
{% extends 'base.html' %}

{% block title %}Catálogo{% endblock %}

{% block content %}
<div class="container" >
    <h3>Listado de libros</h3>
    <!-- Formulario de Búsqueda -->
    <form method="POST" action="{{ url_for('pantallas_generales.catalogo') }}"  enctype="multipart/form-data">
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="Buscar por ISBN o Título" name="busqueda">
            <button class="btn btn-outline-secondary" type="submit" name="btn_buscar">Buscar</button>
        </div>

        
        <!-- Botón para Exportar a CSV -->
        
        <div class="text-end mb-4">
            <a href="{{ url_for('pantallas_generales.calculadora') }}" class="btn btn-outline-primary">Calculadora</a>
            {% if current_user.is_authenticated %}
            <div class="btn-group" role="group" aria-label="Basic outlined example">
                <button type="button" id="btn_importar" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#modalRecordatorioExportar">Importar CSV</button>
                <button type="submit" name="btn_exportar" class="btn btn-outline-primary">Exportar un CSV</button>
                <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#modalAgregarLibro">Agregar Libro</button>
            </div>
            {% endif %}
        </div>
        <!-- Campo para cargar archivos csv -->
        <input type="file" class="input-file-catalogo" name="archivo_csv" id="archivo_csv" accept=".csv"  onchange="this.form.submit()">
       
        

    </form>
    
    <!-- Listado de Libros -->
    <div class="container mt-3">
        {% for libro in libros %}
            {% if loop.index0 % 4 == 0 %}
                {% if not loop.first %}
                    </div>
                {% endif %}
                <div class="row g-3">
            {% endif %}
            <div class=" col-md-3">
                <div class="card h-100  text-center">
                    <img src="{{ libro.url_imagen }}" class="card-img-top" alt="{{ libro.titulo }}">
                    <div class="card-body ">
                        <h5 class="card-title">{{ libro.titulo }}</h5>
                        <p class="card-text">ISBN: {{ libro.isbn }}</p>
                        <p class="card-text">Editorial: {{ libro.editorial }}</p>
                    
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <a href="{{ url_for('pantallas_generales.informacion_libro', id=libro.id) }}" class="btn btn-primary">Más información</a>
                        </li>
                    </ul>
                        {% if current_user.is_authenticated %}
                            <a href="{{ url_for('modificacion_libros.editar_libro', id=libro.id) }}" class="btn btn-outline-primary">Editar</a>
                            <a href="{{ url_for('modificacion_libros.eliminar_libro', id=libro.id) }}" class="btn btn-outline-danger">Eliminar</a>
                        {% endif %}
                </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="container">
        <div class="row">
            <div class="col text-center my-4">
                <hr>
                <p>Última modificación del catálogo: {{ fecha.ultima_modificacion.strftime('%d/%m/%Y %H:%M:%S') if fecha.ultima_modificacion else 'No disponible'  }}</p>
            </div>
        </div>
    </div>

<!-- Modal Agregar Libro -->
<div class="modal fade" id="modalAgregarLibro" tabindex="-1" role="dialog" aria-labelledby="modalAgregarLibroLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="modalAgregarLibroLabel">¿Cómo quiere agregar el libro?</h5>
          <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body d-flex justify-content-around">
          <!-- Botones dentro de la modal -->
          <a href="/agregar_auto" class="btn btn-primary">
            <i class="fas fa-search"></i> <br> Busqueda automática
          </a>
          <a href="/agregar" class="btn btn-secondary">
            <i class="fas fa-pencil-alt"></i> <br> Agregar manualmente
          </a>
        </div>
      </div>
    </div>
  </div>

<!-- Modal Recordatorio Exportar -->
<div class="modal fade" id="modalRecordatorioExportar" tabindex="-1" role="dialog" aria-labelledby="modalRecordatorioExportarLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalRecordatorioExportarLabel">Recordatorio de Seguridad</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Antes de importar un nuevo catálogo, asegúrate de haber exportado el catálogo actual para no perder datos.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary" id="confirmarImportacion">Continuar</button>
            </div>
        </div>
    </div>
</div>


  <script>

document.addEventListener('DOMContentLoaded', function() {
    var importarBtn = document.getElementById('btn_importar');
    var modalRecordatorio = new bootstrap.Modal(document.getElementById('modalRecordatorioExportar'));
    var confirmarBtn = document.getElementById('confirmarImportacion');
    
    importarBtn.addEventListener('click', function() {
        modalRecordatorio.show();
    });

    confirmarBtn.addEventListener('click', function() {
        document.getElementById('archivo_csv').click();
        modalRecordatorio.hide();
    });


    document.getElementById('modalRecordatorioExportar').addEventListener('hide.bs.modal', function (event) {
        var backdrop = document.querySelector('.modal-backdrop');
        if (backdrop) {
            backdrop.remove();
        }
    });
});

</script>
{% endblock %}

Codigos/app/templates/inicio.html
{%extends 'base.html'%}

{%block title%}Inicio{%endblock%}

{%block content%}

<div class="div-style-inicio">
    <img id="imagenletras" class="img-letras-logo rounded" src="../static/img/letras-logo.png" alt="Letras logo">
    <form method="POST" action="{{ url_for('pantallas_generales.inicio') }}"  enctype="multipart/form-data">
        <div class="input-group-style-inicio input-group">
            <input type="text" class="form-control" placeholder="Buscar por ISBN o Título" name="busqueda_inicio">
            <button class="btn btn-secondary" type="submit" name="btn_buscar_inicio">Buscar</button>
        </div>
    </form>
</div>

{%endblock%}